language: csharp
solution: Administration.sln
install:
  - nuget restore Administration.sln
  - nuget install xunit.runners -Version 2.4.1 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Administration/Administration.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Administration.Test/bin/Debug/netcoreapp3.1/Administration.Test.dll
